### PR TITLE
@keycloakify/angular

### PR DESCRIPTION
**Pull request by garronej**

### CODE REVIEW

**Comment by garronej** [comment]
## What I've Done


### CI Setup

I've configured a GitHub Action so that when you bump the version number in `package.json`, it will automatically publish a [GitHub release](https://github.com/keycloakify/keycloakify-angular/releases/tag/v0.0.1-rc.2) and push it to [npm](https://www.npmjs.com/package/@keycloakify/angular).

### Dynamic Linking

You can dynamically link the library to the starter. Here's how:

```bash
git clone https://github.com/keycloakify/keycloakify-angular-starter
git clone https://github.com/keycloakify/keycloakify-angular
cd keycloakify-angular
git checkout @keycloakify/angular # Checking out this branch
yarn
yarn link-in-starter

# In another terminal
cd keycloakify-angular-starter
yarn start
# The changes made in the lib will be visible live
```

### Absolute Import Paths

The import paths are now absolute, enabling page ejection. Components can be copied from the sources to the starter as-is.

The sources look like this:

source-structure

They are compiled back into this:

compiled-structure

You can cherry-pick files from the package as needed:

cherry-pick-example

This setup allows for ejection while ensuring that only the required components are shipped to the client, minimizing page payload.

### Be Careful When Importing From Keycloakify

Make sure to cherry-pick only what you need from Keycloakify. Never use the index files meant for React users.

Also, always import types as types. While not crucial, this helps prevent importing unnecessary content.

```ts
import { type KcContext } from "keycloakify/login/KcContext";
```

For example:

```ts
// Not OK:
import {} from "keycloakify/login/i18n";

// OK:
import {} from "keycloakify/login/i18n/noJsx";
```

### Remaining Tasks

First, is to repatiate the account theme code that I didn't have the courage to bring back. 😬 But you can infer from how the login is layed out.  

One important task remains, which requires Angular-specific expertise. The current provider setup needs reworking.

Keep in mind, from the library's perspective, **you do not know the exact type of `i18n` and `kcContext`**. You only know that it extends the default `KcContext` shape and includes the default message keys. However, it's essential that users can define their own message keys and translations.

Users should also be able to extend `KcContext`, or they won’t be able to use plugins.

From the library's point of view, both the values and the types for `kcContext` and `i18n` are passed as parameters to you. The provider must be generic.

For example, if the user writes:

```ts
/* eslint-disable @typescript-eslint/no-unused-vars */
import { i18nBuilder } from "keycloakify/login/i18n/noJsx";
import { ThemeName } from "../kc.gen";

const { getI18n, ofTypeI18n } = i18nBuilder
    .withThemeName<ThemeName>()
    .withExtraLanguages({}) 
    .withCustomTranslations({
      en: { foo: "value of foo" }
    })
    .build();
```

They should be able to write:

```html
<ng-container headerNode>
    {{ i18n.msgStr("foo") }}
</ng-container>
```

Without receiving a type error.

Making a union of the `I18n` type is not the right approach. For instance, see these lines:

https://github.com/keycloakify/keycloakify-angular/blob/a42332421c05aec460ed12542c57cc97cb37e6bd/projects/keycloakify-angular/src/i18n.ts#L8

https://github.com/keycloakify/keycloakify-angular/blob/a42332421c05aec460ed12542c57cc97cb37e6bd/projects/keycloakify-angular/src/providers/keycloakify-angular.providers.ts#L12-L14

There should be separate providers for login and account. If it's too difficult to implement, it's better to focus solely on login and drop account support for now.

It’s also not acceptable to retrieve `kcContext` from the global object within the library:

https://github.com/keycloakify/keycloakify-angular/blob/8fe66dcc5a50296cb9d03b4c9290b1e39170945c/src/lib/providers/keycloakify-angular.providers.ts#L43

Instead, `kcContext` should be passed as a parameter.

### Importing Guidelines

All imports should be absolute, **except** for the imports of `I18n` and `KcContext` types:

https://github.com/keycloakify/keycloakify/blob/47ca811878cbec21662229b0c638d7b0f0c4be7b/src/login/pages/Login.tsx#L1-L8

These should be relative so that when a page is ejected, it uses the local type (which may have been overloaded by the user).

Your library must export the `KcContext` and `I18n` types at the same location where the page will be ejected.

For example, here's where to export `i18n`:

https://github.com/keycloakify/keycloakify-angular/blob/%40keycloakify/angular/src/login/i18n.ts

And here's where to export `KcContext`:

https://github.com/keycloakify/keycloakify-angular/blob/%40keycloakify/angular/src/login/KcContext.ts

Thus, this line:

https://github.com/keycloakify/keycloakify-angular/blob/05d1d9826eb937793f2189693057d86d6700c6cf/src/login/pages/login/login.component.ts#L16

Should be replaced by:

```ts
import type { KcContext } from "../../KcContext";
```

### Component Structure

Wherever possible, components should be self-contained in a single directory. This makes ejection easier; if components are scattered across locations, it becomes harder to eject them.

Also, the `user-profile-form-field` component should be passed as a parameter to both the registration and user profile pages. Otherwise, users will need to eject all the pages where it is used and manually update the imports. If this is too difficult with Angular, it’s not a dealbreaker.

### Conclusion

You’ve done an impressive job in such a short time, but there is still much work to do to get the `@keycloakify/angular` library ready.

It's worth noting that creating a library with ejectable components is much harder than just having a pre-configured starter. The difficulty is magnitudes higher. So if you’re feeling overwhelmed, it’s perfectly okay to roll back to a clean starter with all components included. Keep it as an option—don’t burn out over this!

Best,

**Comment by luca-peruzzo** [comment]
### Task list

- [x]  absolute/relative imports
- [x]  import type
- [x]  i18n rework
- [ ]  account theme
- [ ]  user profile form field rework

**Comment by luca-peruzzo** [comment]
@kathari00 @garronej here the task list about requested changes

**Comment by luca-peruzzo** [comment]
@garronej @kathari00 all tasks are completed (the question of the template remains).
due to the changes now in starters we have to do something like that depending on the presence of the account theme:
```
          window.kcContext?.themeType === 'account'
            ? provideKeycloakifyAngularAccount({
                classes,
                doUseDefaultCss,
                getI18n: getI18n,
              })
            : provideKeycloakifyAngularLogin({
                classes,
                doMakeUserConfirmPassword,
                doUseDefaultCss,
                getI18n: getI18n,
              }),
```
@garronej is it something you can handle when someone initializes the account theme?

**Pull request closed without merging**
